apiVersion: v1
kind: Secret
metadata:
  name: ztai-portal-stripe
type: Opaque
stringData:
  STRIPE_SECRET_KEY: {{ .Values.stripe.secretKey | quote }}
  STRIPE_PRICE_ID: {{ .Values.stripe.priceId | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.stripe.webhookSecret | quote }}
